### ISSUE TITLE
SetInvalidCertificateAcceptance not entering in if netframework.

### ISSUE THREAD

**Issue by xbarra** [jchristn/WatsonWebsocket#105]
While looking for a workaround to #101, I noticed that in SetInvalidCertificateAcceptance
https://github.com/jchristn/WatsonWebsocket/blob/affc63f0d72d97c61bab9b4e9a2cd97455975849/src/WatsonWebsocket/WatsonWsClient.cs#L569

when running in Net 6.0, the execution entered the if at line 575 (`#if NET || NETSTANDARD || NETCOREAPP`), but when running in Net Framework 4.8, it did not enter into the if at line 571 (`#if NETFRAMEWORK`).

**Comment by jchristn** [comment]
Hi!  Sorry for the delay, I added ```Console.WriteLine("Hello!");``` to both client and server and tested on .NET 4.6.1.  It appears to enter for me.  I'll test on .NET Framework 4.8 next.

![image](https://user-images.githubusercontent.com/1421081/210274898-c3ab476c-3896-4e6f-8640-9b2af4e43852.png)

**Comment by jchristn** [comment]
Hi, I just added targeting for ```net48``` and tested, and it entered correctly.  I'll publish a patch with the proper targeting momentarily.
![image](https://user-images.githubusercontent.com/1421081/210275522-263844ff-f600-4507-b520-e1f1285105a8.png)

**Comment by jchristn** [comment]
Please reopen if the issue continues after upgrading to 4.0.4!

NuGet: https://www.nuget.org/packages/WatsonWebsocket/4.0.4
Commit: https://github.com/jchristn/WatsonWebsocket/commit/ae48a849d6549a93c3382da6887a29e6c2fff44c
