### ISSUE TITLE
ListClients method contains disconnected client on ClientDisconnected event (v4.0.1)

### ISSUE THREAD

**Issue by marco-manfroni-perugiatiming** [jchristn/WatsonWebsocket#108]
Hi and thanks for continue to support this awasome library!
I've seen that when a client connects, the ListClients method called inside the ClientConnected event returns the list with the new client, but when I disconnect a client, the list still contains that client in the ClientDisconnected event.
If I ask for that method later in the code, the list is correct without the disconnected client. Maybe it's not kept in sync until the event is completed.
I'm not sure if by design or bug.
Thanks!

**Comment by jchristn** [comment]
Hi, please try NuGet v4.0.3 and re-open if any issues!  https://www.nuget.org/packages/WatsonWebsocket/4.0.3
