### ISSUE TITLE
Sending text payloads

### ISSUE THREAD

**Issue by jlopvet** [jchristn/WatsonWebsocket#109]
Hello,

First of all thank you for supporting this great library.
Might be my mistake but it seems we cannot send text payloads anymore as the string is always converted to bytes.

Kind Regards,
Jules

**Comment by jchristn** [comment]
Hi @jlopvet I assume this is server-side?  Thanks for letting me know, please try NuGet v4.0.2: https://www.nuget.org/packages/WatsonWebsocket/4.0.2 and reopen if any issues!
