### ISSUE TITLE
TestSslClient and TestSslServer don't exist

### ISSUE THREAD

**Issue by FodderMK** [jchristn/WatsonWebsocket#11]
The `readme` makes mention of a `TestSslClient` and `TestSslServer` but these don't seem to exist in the project.  There is also reference to `test-certificate.txt` but it looks like that was removed on Jun 12 with commit `44e8ace`.  Is the `readme` incorrect or were the files removed by accident?

**Comment by jchristn** [comment]
Hi @FodderMK thanks for pointing that out.  The test projects were collapsed into ```TestClient``` and ```TestServer```, both of which prompt for whether or not SSL should be enabled.  It appears I did (accidentally) remove the test SSL certificate.  I'll make these adjustments and get a commit in right away.

In the meantime please feel free to use the test certificate from WatsonTcp, found here: https://github.com/jchristn/WatsonTcp/tree/master/TestClient

The .txt file should have the passwords, etc.

Thanks again for pointing this out!  Will close once I update the README and get the certs back into the projects.

**Comment by jchristn** [comment]
Actually I recall why I removed them.  It's unnecessary.  WatsonWebsocket uses HTTPS which relies on the certificate store provided by the operating system.  You should only have to enable SSL by setting the bool in the constructor accordingly, and have the certificates loaded into the client and server certificate store.  

I'm updating the README currently; closing this issue now.

Thanks!

**Comment by jchristn** [comment]
Confirmed the presence of the test cert which can be loaded into the OS: https://github.com/jchristn/WatsonWebsocket/tree/master/TestClient

README is updated

**Comment by FodderMK** [comment]
Thanks!
