### ISSUE TITLE
README sample issue

### ISSUE THREAD

**Issue by Exergist** [jchristn/WatsonWebsocket#110]
The README's server example includes `ClientConnectedEventArgs` and `ClientDisconnectedEventArgs`, which seem to have been replaced by `ConnectionEventArgs` and `DisconnectionEventArgs`, respectively. 

Also it looks like `Encoding.UTF8.GetString(args.Data)` should be `Encoding.UTF8.GetString(args.Data.Array)`.

**Comment by jchristn** [comment]
Thanks for letting me know!  I'll get it fixed ASAP
