### ISSUE TITLE
Blazor WASM Support

### ISSUE THREAD

**Issue by ebarale99** [jchristn/WatsonWebsocket#116]
First, thank you for creating this awesome library!.
I have used this package for many windows applications, but now I need to implement a WebSocket connection in a Blazor WASM application, but at the moment it is not supported ('System.PlatformNotSupportedException' when calling the 'Start()' method).
Tested project: Blazor WASM .NET 7. Visual Studio 2022, Windows 11, Web Server Kestrel

**Comment by jchristn** [comment]
Hi @ebarale99 thank you for your kind words!  I don't have any/much experience in Blazor, do you have either A) a minimum project/solution you could share or B) an indication of where the exception was being thrown (full exception details)?  I suspect it's because WatsonWebsocket is using ```http.sys``` under the hood which may be different than Kestrel, but I don't know for sure.

**Comment by ebarale99** [comment]
Hi @jchristn, and thanks for the quick reply. 
The full exception is: 'Operation is not supported on this platform at System.Net.WebSockets.ClientWebSocketOptions.set_Cookies(CookieContainer value) at WatsonWebsocket.WatsonWsClient.StartAsync() at AssemblyStationWeb.Pages.WatsonWebSocket.OnInitializedAsync()'
I tried to run the project with IIS, but there's same error.
I give you a sample project which contains both WatsonWebsocket and System.net.WebSockets implementations.
[AssemblyStationWeb.zip](https://github.com/jchristn/WatsonWebsocket/files/10508431/AssemblyStationWeb.zip)

**Comment by jarlbrak** [comment]
@jchristn Is there a reason modifying the KeepAliveInterval is unsupported in Blazor WASM?

```cs
[UnsupportedOSPlatform("browser")]
      public int KeepAliveInterval
      {
          get
          {
              if (_IsBrowser)
              {
                  throw new PlatformNotSupportedException();
              }

              return _KeepAliveIntervalSeconds;
          }
          set
          {
              if (_IsBrowser)
              {
                  throw new PlatformNotSupportedException();
              }

              if (value < 1)
              {
                  throw new ArgumentException("ConnectTimeoutSeconds must be greater than zero.");
              }

              _KeepAliveIntervalSeconds = value;
          }
      }
```

**Comment by jchristn** [comment]
Did you see the link and reference above?  Not sure what you're asking.

**Comment by berik99** [comment]
This is why it is not supported by the framework's base WebSocket library. Maybe it will be implemented in the future, but at the moment in the tests I did it gave some problems

**Comment by jarlbrak** [comment]
Thanks @berik99. It is odd, there is a websocket connection I am using that tells me they need a keepalive ping every 5 seconds to maintain the connection, but it is clearly working as implemented here with no issues and no disconnects. Not sure why but perhaps Blazor connections just don't need that support? No idea.

**Comment by jchristn** [comment]
@jarlbrak does it specify that it needs a TCP keepalive, or, an application-level message that is used as a heartbeat/keepalive?  Cheers
