### ISSUE TITLE
After compiling net7.0 aot, the client cannot connect to the server

### ISSUE THREAD

**Issue by williamlzw** [jchristn/WatsonWebsocket#123]
.net7.0, vs2022, windows10
After compiling net7.0 aot, the client cannot connect to the server.

**Comment by williamlzw** [comment]
![image](https://user-images.githubusercontent.com/11348670/226791409-80e1d09d-7ce2-4041-bfe5-62bee022d5a1.png)
![image](https://user-images.githubusercontent.com/11348670/226791596-fee872bf-96bf-4f74-a1d2-76dbc4775f05.png)

**Comment by williamlzw** [comment]
SuperSimpleTcp aot runs normally after compilation. It may be that Invoke does not support aot.

**Comment by WarstekHUN** [comment]
@williamlzw Have you already solved the problem? Maybe could you provide some code? Also, maybe you should try it without SSL. Have you tried it with JS from a web-browser? If you have, what was the error message you got?

**Comment by williamlzw** [comment]
Reflection does not support nativeaot
