### ISSUE TITLE
Incorrect #if condition in SetInvalidCertificateAcceptance

### ISSUE THREAD

**Issue by Rubidium37** [jchristn/WatsonWebsocket#127]
in WatsonWsClient.cs, in the method SetInvalidCertificateAcceptance (currently around line 600), there is a conditional compilation directive.

The directive tests for NET, NETSTANDARD and NETCOREAPP.
The wrapped code has a reference to the property [ClientWebSocketOptions.RemoteCertificateValidationCallback](https://learn.microsoft.com/dotnet/api/system.net.websockets.clientwebsocketoptions.remotecertificatevalidationcallback).

Such property is available in NET standard starting from version 2.1.

Therefore, the preprocessor condition should be changed from
`#if NET || NETSTANDARD || NETCOREAPP`
to
`#if NET || NETSTANDARD2_1_OR_GREATER || NETCOREAPP`

**Comment by jchristn** [comment]
Thank you @Rubidium37 - I will make the change!
