### ISSUE TITLE
Dispose Method Makes CPU %100 and hangs

### ISSUE THREAD

**Issue by etempm** [jchristn/WatsonWebsocket#132]
Hi,

WcServer.Stop();
WcServer.Dispose();

If I have more than one client connected, Dispose method makes cpu usage  %100 and hangs. Maybe loop in that?

**Comment by etempm** [comment]
I removed Stop method, and worked.

**Comment by jchristn** [comment]
Hi @etempm thanks for letting me know.  To make sure I understand, when you call ```Stop``` followed by ```Dispose```, the CPU spikes and hangs, but, when you only call ```Dispose```, it does not?

**Comment by jchristn** [comment]
(Re-opening in case there's a fix that I need to apply)

**Comment by jchristn** [comment]
I just tried to replicate this using the ```Test.Server``` and ```Test.Client``` projects.  I was unable to get CPU to spike on ```Stop``` and ```Dispose``` or just ```Dispose``` alone.
![image](https://github.com/jchristn/WatsonWebsocket/assets/1421081/85ca8db2-4f78-459e-97ab-54cd7ac09891)

Please let me know if you are able to reliably reproduce this behavior, I'd love to fix it!

Cheers, Joel

**Comment by etempm** [comment]
Thank you. It is not always being. By the way, Dispose method also calls stop, son not important for me. I deleted stop method and no problem now.
