### ISSUE TITLE
[WatsonWsServer] non-websocket request rejected from ...

### ISSUE THREAD

**Issue by besttof** [jchristn/WatsonWebsocket#138]
No matter what I do (for example run the example from https://github.com/jchristn/watsonwebsockettest), the server logs:

> [WatsonWsServer] non-websocket request rejected from ::1:53844

Where the `::1:53844` part is different each time, and definitely not the port I set the client to use. It feels like there is some setup missing, but I can't find what.

For completeness' sake, this is the full output if I run the example and connect the log action to `Console.WriteLine`

```
[WatsonWsServer] starting on: http://localhost:8181/
[WatsonWsServer] non-websocket request rejected from ::1:53843
Sending message from client to server...
[WatsonWsClient] not connected
[WatsonWsClient] dispose complete
Client disconnected from server
Sending message from server to client...
[WatsonWsServer] unable to find client 00000000-0000-0000-0000-000000000000
Press ENTER to exit
```

PS another surprising find was that the `Encoding.UTF8.GetString(e.Data)` overload does not seem to exist, so I had to write my own extension method. Which adds to the "there must be something missing"-feeling...

**Comment by jchristn** [comment]
Hi @besttof a few questions for you.  1) what operating system are you using?  2) what runtime are you using?  3) what client are you using?

**Comment by jchristn** [comment]
And if you clone the repository, what happens when you use the Test.Server and Test.Client repositories?

**Comment by besttof** [comment]
> Hi @besttof a few questions for you. 1) what operating system are you using? 2) what runtime are you using? 3) what client are you using?

Yeah, fair question I should've included those in the initial report. My bad.

Running on `macOS 13.2.1 (22D68)`, framework is `Mono 6.12.0 Stable` (reluctantly, dotnet core has some issues with running a build that I need to figure out) and with client I assume you mean the websocket client? I tried both the example repo linked above and just call the werver with some basci js `WebSocket` calls.

**Comment by besttof** [comment]
Never mind, the issue was that I somehow created a .net framework project. In a new .net (core) project it works fine.
