### ISSUE TITLE
Client connects to server although there is no server running

### ISSUE THREAD

**Issue by wirmachenbunt** [jchristn/WatsonWebsocket#18]
just try the test client with default values
![image](https://user-images.githubusercontent.com/1138673/70397419-51a93a80-1a12-11ea-9862-baa193bd4f50.png)

**Comment by jchristn** [comment]
Interesting, thanks for letting me know.  I will debug it ASAP.  Thanks!

**Comment by jchristn** [comment]
Looks like my AfterConnect method needs to do some processing based on the ClientWebSocket.State parameter.  On my list, thanks for bringing this up!

**Comment by jchristn** [comment]
Let me know if this works better for you!

NuGet v2.0.2: https://www.nuget.org/packages/WatsonWebsocket/2.0.2
Commit: https://github.com/jchristn/WatsonWebsocket/commit/71e7ea3b927196c96a83a1a778568df4ba4091eb

**Comment by wirmachenbunt** [comment]
Okey dokey, i‘ll check the fix later the day. thanks for the swift reply.

**Comment by wirmachenbunt** [comment]
it works, very cool. thanks
