### ISSUE TITLE
send message to server does not work

### ISSUE THREAD

**Issue by wirmachenbunt** [jchristn/WatsonWebsocket#19]
![image](https://user-images.githubusercontent.com/1138673/70397460-a947a600-1a12-11ea-89e3-c29dc4147ca5.png)

**Comment by jchristn** [comment]
Hi @wirmachenbunt try typing ```send```, pressing enter, then typing your message.  Should work great :)

Cheers, Joel

![image](https://user-images.githubusercontent.com/1421081/70401189-615d5a80-19e3-11ea-8b7d-e6cc6d462c95.png)

**Comment by wirmachenbunt** [comment]
Oops, my fault. i mixed things up. No issue at all.
