### ISSUE TITLE
Mono client on Debian isn't protocol compliant

### ISSUE THREAD

**Issue by BryanCrotaz** [jchristn/WatsonWebsocket#2]
Windows server, Debian client on Raspberry Pi

Error on server side: `Invalid data format for the specific protocol operation`

This is happening in the ClientWebSocket. I suspect an endianness or Mono issue. Same client code works fine on Windows.

**Comment by BryanCrotaz** [comment]
I've used WebSocket4Net as a replacement client - you might find clues in their code as to how to make a client that runs on Windows and Linux

**Comment by jchristn** [comment]
Thanks @BryanCrotaz I will queue this up.  It's on my list.
