### ISSUE TITLE
Connection on real network not working

### ISSUE THREAD

**Issue by tgd-git** [jchristn/WatsonWebsocket#20]
I tried to connect from another PC on the LAN and can not get it working. Using the provided testserver and client. 

Client just printing "Server disconnected" on connection attempt.
Firewalls on both machines down.

Connections from same PC (127.0.0.1) work as expected.

**Comment by jchristn** [comment]
Hi, what IP address are you using to instantiate the server?  Try ‘’’*’’’, ‘’’0.0.0.0’’’, or the actual interface IP. 

Let me know!

**Comment by tgd-git** [comment]
I tried the actual interface IP (192.168.2.107) and also 0.0.0.0 as admin. same result still :(
Client is on the same network of course with IP 192.168.2.190

**Comment by tgd-git** [comment]
Tried again and it only works with *. Apparently i must have forgot to start as admin when i tried * the first time. Sorry for that.
Any way to get the server running without elevating rights?

**Comment by jchristn** [comment]
On what port are you listening?  Elevation is required when listening on IPAddress.Any (ie * + or 0.0.0.0) or if you are listening on a port under 1024. 

Glad it’s working at least as a start!

**Comment by tgd-git** [comment]
I tried different ports, but non in the reserved range. Sticking with 1500 for now.
Just want avoid elevation that is apparently needed for the *.
Would be happy if 127.0.0.1 or the interface IP would work. Thanks for the swift support btw!

**Comment by jchristn** [comment]
Sorry for the delay @tgd-git, I was traveling today.

You may have to use netsh to add a URL ACL for the specified hostname and port, i.e.

```netsh http add urlacl url=http://192.168.2.107:1500/```

It might also require that you specify the user account under which you want to allow the binding.

I have a small-ish reference on this in the WatsonWebserver repository here: https://github.com/jchristn/WatsonWebserver/wiki/Using-SSL-on-Windows

See specifically the 'Check for Existing Bindings' and 'Add the Binding' section.  Since WatsonWebsocket is using the same http.sys under the hood, these should also be appropriate.  

Please let me know if this helps!  Cheers, Joel

**Comment by jchristn** [comment]
Hi @tgd-git - I should add that these issues (elevated privileges, having to use netsh) are Windows issues and exist for anything that uses http.sys under the hood.  I didn't want to leave you with the impression that you had to do these gymnastics for only this piece of software :)  Cheers

**Comment by tgd-git** [comment]
hi dont worry, i was assuming it is something .net/windows related but maybe can be overcome somehow. still have to try the binding workaround but for now it worked with the elevation and was good enough for some prototyping and testing. thank you for putting this all together, its nice to work with so far! will report on the bindings. 
also would suggest that you put the findings here (how to start the server to be connectable from other machines) into the readme. these windows limitations are not that well known i guess.

**Comment by jchristn** [comment]
Great suggestion @tgd-git I will do that!  I'll close this but please re-open it if needed.  Cheers
