### ISSUE TITLE
ClientConnectedEventArgs.HttpRequest.get returned null

### ISSUE THREAD

**Issue by Danatobob** [jchristn/WatsonWebsocket#22]
Version 2.1.1 from NuGet
for ClientConnected event I get this

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
WatsonWebsocket.ClientConnectedEventArgs.HttpRequest.get returned null.
```

**Comment by jchristn** [comment]
Looking into it momentarily!

**Comment by jchristn** [comment]
Please let me know if this does or does not resolve the issue for you.

NuGet v2.1.2: https://www.nuget.org/packages/WatsonWebsocket/2.1.2
Commit: https://github.com/jchristn/WatsonWebsocket/commit/097db6e73811056ce9de71fa1e5dfe62f177937a

Cheers!

**Comment by Danatobob** [comment]
Seems to be working fine now. Thanks.
