### ISSUE TITLE
Is ClientConnected Premature

### ISSUE THREAD

**Issue by AK5nowman** [jchristn/WatsonWebsocket#25]
Hello,

I'm using this library to host a playground while I learn javascript. I've noticed that the ClientConnected event is called before the client is initialized and added to the collection. Is there a reason why the ClientConnected event would be called so early when there are a few instances where the client wouldn't actually be accepted? 

I'm also using your SimpleTCP library in another project and the ClientConnected event is the last thing to be called when accepting a connection. I only program as a hobby so I wouldn't know what to look for to determine if this is because of fundamental differences between Web and TCP socket.

Thank you!

**Comment by jchristn** [comment]
Hi @AK5nowman thanks for filing this!  I’m moving this week and will do my best to get to it by early this coming week!  Cheers Joel

**Comment by jchristn** [comment]
Hi @AK5nowman this is fixed!

Please see NuGet v2.1.5: https://www.nuget.org/packages/WatsonWebsocket/2.1.5
And this commit: https://github.com/jchristn/WatsonWebsocket/commit/0d1b27a4e565c76af016b3bac7a374f7180bb037

Please re-open if you feel there is more to do on this one.

Thanks for bringing this issue up!

Cheers, Joel
