### ISSUE TITLE
Communication with JS websockets

### ISSUE THREAD

**Issue by matkoch** [jchristn/WatsonWebsocket#26]
_Thanks for your work with this library. Really appreciate it._

I'm trying to communicate with a JS WebSocket. Roughly like:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <!-- <script src="app.js" type="text/javascript"></script> -->
    <script type="text/javascript">
        var socket = new WebSocket('http://localhost:8083/socket');
        socket.onopen = function() {
           // alert('handshake successfully established. May send data now...');
		   socket.send("Hi there from browser.");
        };
		socket.onmessage = function (evt) {
                //alert("About to receive data");
                var received_msg = evt.data;
                alert("Message received = "+received_msg);
            };
        socket.onclose = function() {
            alert('connection closed');
        };
    </script>
</body>
</html>
```

But `http://` is not supported: `SyntaxError: An invalid or illegal string was specified`

[This SO question](https://stackoverflow.com/questions/52757238/c-sharp-httplistener-prefixes-not-accepting-ws-preventing-js-websocket-to-conn) seems to be related, but I still couldn't make it work.

Do you have any hints?

**Comment by jchristn** [comment]
Hi @matkoch please try changing ```var socket = new WebSocket('http://localhost:8083/socket');``` to ```var socket = new WebSocket('ws://localhost:8083/socket');```.  I took a screenshot below showing it working on mine using the ```TestServer``` project.

![image](https://user-images.githubusercontent.com/1421081/81524344-ab859780-9305-11ea-9c29-011c5b69703b.png)

Please let me know if this works!

**Comment by matkoch** [comment]
Interestingly, it does only work in Chrome, but not in Firefox.

**Comment by jchristn** [comment]
Is this what you get in Firefox?
```
var socket = new WebSocket('ws://localhost:8000/socket');
[Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line 1"  data: no] debugger eval code:1:14
    <anonymous> debugger eval code:1
Content Security Policy: The page’s settings blocked the loading of a resource at ws://localhost:8000/socket (“connect-src”). debugger eval code:1:13​
```

It may be related to this: 
![image](https://user-images.githubusercontent.com/1421081/81581124-29c45700-9363-11ea-81e3-8a5d9c94a483.png)

Discovered these: https://stackoverflow.com/questions/37298608/content-security-policy-the-pages-settings-blocked-the-loading-of-a-resource
and
https://github.com/eclipse/che/issues/13736

**Comment by jchristn** [comment]
Oh!  Try going to another page.  When I first went to my own site (www.joelchristner.com) i.e. any site that doesn't have this content security policy meta tag, it worked!
![image](https://user-images.githubusercontent.com/1421081/81581465-a0f9eb00-9363-11ea-9356-baac808ad98f.png)

**Comment by jchristn** [comment]
Also interesting to note that Chrome starts outbound websocket connections using IPv6 whereas Firefox is using IPv4.

**Comment by jchristn** [comment]
Going to close this, hope it helps.  Seems the library is behaving as it should.  Please re-open if you have further issues @matkoch !

**Comment by matkoch** [comment]
Yep. Thanks for your response! I use this only in combination with CEF, so I’m good :)
