### ISSUE TITLE
Proxy support ?

### ISSUE THREAD

**Issue by varunistar** [jchristn/WatsonWebsocket#28]
Hello, I'm working on a windows forms application where I have a requirement to connect to a WebSocket connection,  I  have tried WebSocket-sharp and websocket4net  both libraries are not very well maintained now
So the problems which I faced using them are
- They don't seem to offer good support for proxy connections 
- And they are not maintained now.

So  my question is can **WatsonWebsocket** connect through the system proxy without explicitly providing any proxy credentials (The client which we are working has enabled proxy in their system HTTP request were working fine, but now the websocket)

**Comment by jchristn** [comment]
Hi @varunistar it looks like the underlying library ```ClientWebSocket``` supports this, but I have not implemented: https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocketoptions.proxy?view=netcore-3.1

You're welcome to put together a PR on this; if you prefer I do it, I'll add it to my backlog and will work on it as I can.  Let me know.

Cheers, Joel

**Comment by jchristn** [comment]
Hi @varunistar I took a look through the ```ClientWebSocketOptions``` class in the underlying ```ClientWebSocket``` class used by WatsonWebsocket.  It looks like this exposes only ```get``` capabilities and requires that the proxy be configured under the system config.  So I can't explicitly set this in code.  

Have you tested the system proxy with WatsonWebsocket and had issues?  I'll test it on my end to see if it works.

**Comment by jchristn** [comment]
I was able to get it working with the system proxy (using Charles Proxy):
![image](https://user-images.githubusercontent.com/1421081/83036649-ba4f9800-9fef-11ea-9151-2c42c084b9a8.png)

And...
![image](https://user-images.githubusercontent.com/1421081/83036707-cc313b00-9fef-11ea-8d28-ff5b4de41b1c.png)

**Comment by varunistar** [comment]
No, i haven't tested it, I will get back to you once I test it, Since you are using ClientWebSocket class I think it should take the system proxy automatically because HttpWebRequest takes the system proxy without specifying anything, it used to throw 405 status code when the proxy is auth based anyways ill check from my end.

**Comment by jchristn** [comment]
Ok thanks @varunistar I don't have a proxy that I can test with that uses credentials (unless there's a system setting you can recommend with which I'm not familiar).  It seems to be working ok here using Charles Proxy (I would assume the same for Fiddler).

**Comment by varunistar** [comment]
Can you try it with Authentication based proxy ?

**Comment by jchristn** [comment]
Also with Fiddler:
![image](https://user-images.githubusercontent.com/1421081/83037351-8a54c480-9ff0-11ea-94a1-db1b93e58aee.png)

![image](https://user-images.githubusercontent.com/1421081/83037318-8032c600-9ff0-11ea-8eee-e77edc5ee9c2.png)

Which authentication-based proxy?

**Comment by varunistar** [comment]
Suppose if a proxy server is authentication based it need some credentials in order for the requests to pass in via proxy server,
When you enter the proxy address in the system settings, and when you try to  open chrome or any application, that application will show a dialog where u can enter the credentials, after entering that particular application will use those credentials for every request it makes from that application.

**Comment by jchristn** [comment]
Sorry @varunistar I don't have a way to test that.  I don't know how I would go about testing it either unfortunately.

**Comment by varz29** [comment]
It's ok I'll test it and make a PR if possible and get back to you , thank you for the support 👍

**Comment by varz29** [comment]
I'm @varunistar

**Comment by jchristn** [comment]
Sounds good @varz29 @varunistar cheers!  Will do my best to support you in whatever way I can.

**Comment by jchristn** [comment]
(misclick)
