### ISSUE TITLE
Send vs SendAsync

### ISSUE THREAD

**Issue by joreg** [jchristn/WatsonWebsocket#29]
hei joel,

is there a reason why this library has only SendAsync functions while the very similar SimpleTcp has only Send (non-async) versions? Shouldn't both make sense in both cases?

**Comment by jchristn** [comment]
Hi @joreg - thanks for your question.  Easy answer; the underlying ```ClientWebSocket``` class only implements *Async methods.  So there are no sync methods to expose.  You can always use ```.Wait()``` if needed (but of course, check to make sure it doesn't create complications for your code).  Cheers, Joel
