### ISSUE TITLE
listening on 0.0.0.0 as non-admin

### ISSUE THREAD

**Issue by joreg** [jchristn/WatsonWebsocket#30]
hei joel,

under "Accessing from Outside Localhost" you write: "If you want to listen on more than one hostname or IP address, use * or +. You MUST run WatsonWebsocket as administrator for this to work (this is an operating system limitation)"

my questions:
* is there a difference between * and + and how do they relate to 0.0.0.0?
* i've previously used the [fleck websocket server](https://github.com/statianzo/Fleck) where it is possible to listen on 0.0.0.0 without running as admin. so i wonder if there shouldn't also be a way with watson to do so?!

**Comment by jchristn** [comment]
Hi @joreg how are you doing?  Thanks for your note.

For your two questions:
1) The difference between * and + really comes down to whether or not the HttpListener will bind over the top of previous bindings.  This StackOverflow answer may help: https://stackoverflow.com/questions/12122311/whats-the-difference-between-the-and-with-httplistener
2) In my experience, I have not been able to do this.  Please feel free to give it a try, and if you can, please let me know!  I'll add it to my list but it will be a bit before I can test it.

Cheers, Joel

**Comment by jchristn** [comment]
Just tried 0.0.0.0 again as non-admin; it did not work.

**Comment by joreg** [comment]
thanks for the answer regarding 1). interesting. 

regarding 2) i seem to have found an answer: the above mentioned Fleck webserver implementation, where it works to listen on 0.0.0.0 without being admin, mentions particularly: "Fleck has no dependency on HttpListener or HTTP.sys". so this limitation may come from that dependency, which WatsonWebsocket has and Fleck somehow found a different implementation without that restriction.
