### ISSUE TITLE
killClient has gone in v2?

### ISSUE THREAD

**Issue by BryanCrotaz** [jchristn/WatsonWebsocket#32]
I'm upgrading to the NuGet library to get .Net Standard.
What's the replacement/workaround for `Server.KillClient` that was there in v1?

**Comment by jchristn** [comment]
Hi @BryanCrotaz - ```DisconnectClient``` should do the trick.  Cheers, Joel

**Comment by BryanCrotaz** [comment]
Ta muchly.
