### ISSUE TITLE
Client message is raw byte array, no idea if it's text or binary

### ISSUE THREAD

**Issue by jjxtra** [jchristn/WatsonWebsocket#33]
When receiving a client message on a server, we need a data type of text or binary so we can determine if the byte[] is actual text or really binary.

**Comment by jchristn** [comment]
Good catch.  I'll modify the client to set the WebSocketMessageType enum accordingly.
```
await _ClientWs.SendAsync(new ArraySegment<byte>(data, 0, data.Length), WebSocketMessageType.Binary, true, CancellationToken.None);
```
and I'll modify the ```MessageReceived``` args to include the type.

**Comment by jchristn** [comment]
Hi @jjxtra please check out v2.2.0 on NuGet: https://www.nuget.org/packages/WatsonWebsocket/2.2.0
Commit: https://github.com/jchristn/WatsonWebsocket/commit/9dbcf2461189755e96415da84a238d62d37186ab

The ```MessageReceivedEventArgs``` now has a property called ```MessageType``` which is either ```Text``` or ```Binary```.

Using the ```SendAsync``` method with a ```string``` for input will set this to ```Text``` whereas using a ```byte[]``` will set it to ```Binary```.

Please let me know if this works for you!

Cheers, Joel

**Comment by jjxtra** [comment]
This is great, thank you!
