### ISSUE TITLE
Sending binary data directly as text is no longer possible

### ISSUE THREAD

**Issue by jjxtra** [jchristn/WatsonWebsocket#34]
Prior to 2.2.0, this is how text messages were sent with binary data:

```
server.SendAsync(EndPoint, bytes, System.Net.WebSockets.WebSocketMessageType.Text);
```

In 2.2.0, this signature is gone, requiring one to use this signature:

```
server.SendAsync(EndPoint, System.Text.Encoding.UTF8.GetString(bytes));
```

There is an overload that takes a string, but this requires an extra step to decode the bytes into a string. Seems like this step could be skipped if the internal web socket code could just send the bytes but mark it as text instead of binary.

**Comment by jchristn** [comment]
Hi @jjxtra are you advocating that I bring back the methods that take either string||byte[] as input as well as a WebSocketMessageType parameter?  Cheers, Joel

**Comment by jjxtra** [comment]
You could probably keep the two methods, but add an optional type parameter for the byte[] version that defaults to binary.

**Comment by jchristn** [comment]
Hi @jjxtra - just pushed v2.2.0.1 to NuGet which adds the ```(byte[] data, WebSocketMessageType msgType)``` variant for ```SendAsync```.  Please let me know if this is appropriate!  Cheers, Joel

NuGet: https://www.nuget.org/packages/WatsonWebsocket/2.2.0.1
Commit: https://github.com/jchristn/WatsonWebsocket/commit/e8294b0ef56ef4bc52f24f24446920e53261f8ab

**Comment by jjxtra** [comment]
Looks perfect :)
