### ISSUE TITLE
Is this going to work with .NET 5?

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonWebsocket#42]
I notice this library depends on HttpListener (which I believe was deprecated some time ago).  Will that create a problem for .NET 5?

I've read controversy over the deprecation of HttpListener.  There have been some other projects started to write new lightweight Http servers that run on mono and core.

**Comment by jchristn** [comment]
Hi @pha3z I've been planning to migrate the guts of this library over to https://github.com/jchristn/httpserverlite since it just uses a TcpListener, but haven't gotten around to it.  Cheers, Joel

**Comment by jchristn** [comment]
Accidentally closed, re-opened and labeled as enhancement

**Comment by pha3z** [comment]
Joel, you are awwwesome!  So excited for this!!

I'm finally about to contribute my first open source library to the community.  Its an Return Result library.  I will let you know about it after I've posted it.

**Comment by jchristn** [comment]
Thanks James :) just a heads up I've almost put the finishing touches on the HTTP library that it will use. Once it's done I'll be looking at moving this library over to it. Cheers!

**Comment by jchristn** [comment]
Hi @pha3z good news, .NET 5 doesn't (yet) age out the ```HttpListener``` class.  Just added .NET 5 support (will be pushing shortly).  I haven't yet migrated to my own HTTP library, and would love to get your feedback on it if you're interested.  Cheers, Joel
