### ISSUE TITLE
Combine both websocket server and client

### ISSUE THREAD

**Issue by zydjohnHotmail** [jchristn/WatsonWebsocket#43]
Hello:
I have one special request, I need some help.
I need some kind of web socket relay program. I have one very fast web socket data source, the server is not in my control. But the external web socket server generates huge amount of text data, I can write one web socket client to receive the huge amount of data, but less than 10% of the data is needed. As the external web socket server generates too much data, my web socket client is always freeze, yet less than 10% of the data is useful.
I want to write a web socket relay program, which is one web socket client for the external web socket server, but at the same time, acts as one internal web socket server, send only those 10% useful data to another web socket client.
Another web socket client can process all the useful data. In this design, the web socket relay program will be busy to process all the web socket data, but another web socket client will not be freeze to process only 10% of total data received.
Let me know if my thinking is practical, if yes, can you provide some code example.
Thanks,

**Comment by jchristn** [comment]
Hi @zydjohnHotmail I sent the link so you could see the library and try to put something together, and if it doesn't work, file an issue.  I'm happy to help if you have issues with the library, but I'm not going to build your app for you.  Cheers
