### ISSUE TITLE
Broadcasting to connected clients

### ISSUE THREAD

**Issue by rajeshdua123** [jchristn/WatsonWebsocket#48]
Hi,

How can we broadcast a message to all connected clients?  

Thanks

**Comment by pha3z** [comment]
When each client connects, the ipPort of the client is included.

It is already expected that you will need to implement your own method of tracking clients so you can handle individual connected clients.

Therefore, after you implement some data structure for managing connected clients, it would be easy for you to write a simple method that lets you call server.Send(ipPort, msg) in a loop for every client in your data structure.

**Comment by rajeshdua123** [comment]
I have already done that.  But the fear is that we are expecting 100K clients.  We already have 10K clients connected.

 Wouldn't that loop take a longer time.

I am trying my hands on executing Sendasync with fire and forget mechanism using Task factory.  Not sure if that would help.

**Comment by jchristn** [comment]
Hi @rajeshdua123 if I were to implement this in the library, I'd be doing exactly that: looping.

**Comment by pha3z** [comment]
> I have already done that. But the fear is that we are expecting 100K clients. We already have 10K clients connected.
> Wouldn't that loop take a longer time.

What you are asking for is a network solution, not a server solution.  You're looking for something like multi-casting, where you can send data from a server to some device on a network and that device will forward the data to any number of other remote endpoints.

Processors are limited by the physical core executing instructions.  Even if you have 32 cores, you're limited to processing 32 transmissions simultaneously... and even then, you will be limited by what can go over the bus and ethernet line.

I believe there are special networking devices designed to help overcome these limitations by duplicating the physical data channels on the metal/circuit-board to allow you to send data in mass parallel when driven from a single core.  We are talking specialty network equipment here.

If you want to write some .NET code and throw it on a regular server running RISC processors, you are going to need multiple servers to handle the kind of data push you're looking for.

**Comment by pha3z** [comment]
@rajeshdua123 
FYI: You could always hire myself and the consultant agency I work with.  We have high-end talented network engineers on board that know way more than I do even. :) We're a tiny, agile group of only 5 engineers.

**Comment by jchristn** [comment]
@rajeshdua123 - @pha3z makes an excellent point.  For that many connections, I don't know that an in-software solution is really going to do it for you.  You may want to look into multicast.
