### ISSUE TITLE
Unable to make minimal example work. Am I to upgrade the http connection manually first?

### ISSUE THREAD

**Issue by N0K0** [jchristn/WatsonWebsocket#49]
Hi! I'm trying to use WatsonWebsocket with Unity, but I have some issues getting started.

**Server:**
```C#
using UnityEngine;
using WatsonWebsocket;

public class WebSocketServer : MonoBehaviour
{
    
    private string address = "127.0.0.1";
    private ushort port = 13337;

    private WatsonWsServer _ws;

    private void Awake()
    {
        string header = "[Server] ";
        _ws = new WatsonWsServer(address, port, false)
        {
            Logger = Debug.LogError
        };
        _ws.Start();
    }

    // Update is called once per frame
    void Update()
    {
        Debug.Log(_ws.IsListening);
    }
}

```

Client (fetched from websockets documentation):
```python
import asyncio
import websockets


async def hello():
    uri = "ws://127.0.0.1:13337"
    async with websockets.connect(uri) as websocket:
        await websocket.send("test")
        recv = await websocket.recv()

asyncio.get_event_loop().run_until_complete(hello())

```

**Error log:**
```
[WatsonWsServer] starting http://127.0.0.1:13337/
UnityEngine.Debug:LogError(Object)
WatsonWebsocket.WatsonWsServer:Start()
WebSocketServer:Awake() (at Assets/Scripts/WebSocketServer.cs:21)

True
UnityEngine.Debug:Log(Object)
WebSocketServer:Update() (at Assets/Scripts/WebSocketServer.cs:27)

[WatsonWsServer] non-websocket request rejected from 127.0.0.1:22270
UnityEngine.Debug:LogError(Object)
WatsonWebsocket.<AcceptConnections>d__47:MoveNext()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

Assets\Scripts\WebSocketServer.cs(14,16): warning CS0219: The variable 'header' is assigned but its value is never used

```

From what I see in the source it seems like `IsWebSocketRequest` fails first, and then the connection is rejected since I haven't defined a HttpHandler?

https://github.com/jchristn/WatsonWebsocket/blob/937edf72ba842d226bf2501e633c9845bc4d7433/WatsonWebsocket/WatsonWsServer.cs#L376-L388

**Comment by jchristn** [comment]
Hi, which operating system for client and server?

**Comment by N0K0** [comment]
Hi!
Windows 10, client is on localhost too

**Comment by jchristn** [comment]
Hi @N0K0 could you start the ```Test.Server``` project, and from a browser, open the inspector, and add the following JS and see if it works?
```
let socket = new WebSocket("ws://localhost:9000/");
socket.onopen = function () { console.log("success"); };
socket.onmessage = function (msg) { console.log(msg.data); };
socket.onclose = function () { console.log("closed"); };
```
It sounds like the client isn't sending a websocket request (which is why I asked about the OS version, since Win7 doesn't support websockets)

You should see something like the following:
![image](https://user-images.githubusercontent.com/1421081/100297427-83792100-2f43-11eb-8c67-2d4aa2132169.png)

**Comment by N0K0** [comment]
Hmm, your client worked!
Some pictures from Wireshark.
Good request from your client:
![image](https://user-images.githubusercontent.com/13900053/100522797-d81ed500-31ab-11eb-8a26-40c194d2259b.png)

Bad request from Python Websockets
![image](https://user-images.githubusercontent.com/13900053/100522808-e836b480-31ab-11eb-85c3-1925cd817a2e.png)

Going to see what happens if i manage to remove the extra extensions

**Comment by jchristn** [comment]
Hi, if that's on the same system, that indicates to me that the python client isn't using the underlying OS web socket implementation. Maybe a missing library?  Cheers, Joel

**Comment by jchristn** [comment]
Also notice the HOST header difference. Try with local host instead of 127.0.0.1

**Comment by N0K0** [comment]
Hi! Yeah, from further debugging with your Test.Server and my client I can verify that the issue is somewhere in how the Unity framework works (guessing it's something with the method calls/threading inside the game engine). I think we can close this issue as it stands right now :) 

How do you feel about adding a section to your wiki if I ever figure this out? :D

**Comment by jchristn** [comment]
I'd love to!  Http.sys is definitely sensitive to mismatches in the HOST header vs the listener hostname. Would love to add to the wiki!

**Comment by N0K0** [comment]
Super! Closing this issue for the time being! :)

**Comment by liesauer** [comment]
cannot connect to the server that is started in unity either. [WatsonWebsocketTest](https://github.com/jchristn/WatsonWebsocketTest) works fine though.
```
server = new WatsonWsServer("localhost", 5566);
server.ClientConnected += ClientConnected;
server.ClientDisconnected += ClientDisconnected;
server.MessageReceived += MessageReceived;
server.Start();
```
HttpListenerContext.Request.IsWebSocketRequest always false, even use the JS test code.

![image](https://user-images.githubusercontent.com/8676741/125470932-2819eaaa-8b51-48a5-9be8-6155b9e55e28.png)

**Comment by jchristn** [comment]
Which OS and runtime?

**Comment by liesauer** [comment]
> Which OS and runtime?

it looks like it is not a OS-specific issue, the problem is that Mono does not implement `HttpListenerContext.Request.IsWebSocketRequest`.
![image](https://user-images.githubusercontent.com/8676741/125473160-54644570-dc14-45b2-a2f1-e3bd73bd5d8b.png)

**Comment by jchristn** [comment]
Can you try with .NET Core or .NET 5?

**Comment by liesauer** [comment]
> Can you try with .NET Core or .NET 5?

actully, i am a mod developer not a game developer, so i am limited under .NET 4.6. i am looking for another solution.
