### ISSUE TITLE
Websocket URLs

### ISSUE THREAD

**Issue by AllonisDave** [jchristn/WatsonWebsocket#50]
Will this project work with Websockets with long urls like
wss://192.168.0.123:8002/api/v2/channels/samsung.remote.control?name=xyzzy

If yes, how to set up the client?

**Comment by jchristn** [comment]
Hi @AllonisDave thanks for your question.

I've amended the server to allow you to specify a ```Uri``` on which you wish to listen, so it will work.

What I'm unable to figure out (yet) is how to get it to listen on a base URL, i.e. ```/test``` and also have it pick up incoming websocket requests to ```/test/foo```.  

I've published the update with the Uri-based constructor to NuGet: https://www.nuget.org/packages/WatsonWebsocket/2.2.0.9
And the commit (which also has updated test client and test server projects): https://github.com/jchristn/WatsonWebsocket/commit/aaf295c102814a6e0ab42c3b5f837818ab7131d6

I'll see what I can do to find support for accepting connections from other URLs, and if it's possible, how I pass that context into the consuming application.

**Comment by jchristn** [comment]
Quick update, I just confirmed that you can start the server without specifying a URL i.e. ```new Uri("http://localhost:9000")```, and, specify that the client connect to a specific URL i.e. ```new Uri("http://localhost:9000/test/")``` and *the client will connect and be able to exchange data with the server*.  

I'll need to look into how to supply specific elements from the ```HttpListenerContext.Request``` up to your application so you can see the URL, headers, and query.

**Comment by jchristn** [comment]
Updated the ```Test.Server``` event for ```ClientConnected``` to show how this can be done.

![image](https://user-images.githubusercontent.com/1421081/101223796-aee5c500-3641-11eb-9617-60e8e7473c72.png)

```csharp
        static void ClientConnected(object sender, ClientConnectedEventArgs args) 
        {
            Console.WriteLine("Client " + args.IpPort + " connected using URL " + args.HttpRequest.RawUrl);
            _LastIpPort = args.IpPort;
        }
```

Closing this one out, please re-open if you feel this doesn't address the concern!
