### ISSUE TITLE
Getting error while try start server from outside localhost

### ISSUE THREAD

**Issue by ntdat99** [jchristn/WatsonWebsocket#60]
I try to start WatsonWsServer with ip and port are allow firewall and already add ACL URL.
Here is my code:
                WatsonWsServer server = new WatsonWsServer(_ip, _port,true);

                server.MessageReceived += OnMessage;
                server.ClientConnected += Server_ClientConnected;
                server.ClientDisconnected += Server_ClientDisconnected;
                log.Info("Begin start socket server");
                server.Start();

and i get this error.
`Failed to listen on prefix 'https://{ip}:1234/' because it conflicts with an existing registration on the machine.`
 I already check netstat and port is not using at anywhere else. How can i fix it

**Comment by jchristn** [comment]
Please share the statements you used to add the urlacl and see if there are any conflicting urlacl in the list. Are you running as a regular user or admin?

**Comment by ntdat99** [comment]
> Please share the statements you used to add the urlacl and see if there are any conflicting urlacl in the list. Are you running as a regular user or admin?

im using this by open cmd as administrator
`netsh http add urlacl url=http://ip:1234/ user=everyone listen=yes`

**Comment by jchristn** [comment]
Are there any conflicting entries?

**Comment by ntdat99** [comment]
> Are there any conflicting entries?

Thanks for your support, I already fix it. It work now
I searching and try many way, and suddenly it work
anyway thankyou

**Comment by jchristn** [comment]
Oh, awesome.  I'm glad you got it working @ntdat99 - Cheers!
