### ISSUE TITLE
SendAsync - Taking High CPU 

### ISSUE THREAD

**Issue by rajeshdua123** [jchristn/WatsonWebsocket#64]
Hi Joel,

I have installed the latest version available on Nuget.  The socket server was running pretty fine till yesterday.  From today morning, we are experiencing a high CPU usage while sending the data packets to the connected clients. 

Can you please help?

Thanks

**Comment by jchristn** [comment]
Hi @rajeshdua123 thanks for your note.  I'm having a hard time reproducing this on my side using ```SendAsync```.  Can you provide steps to reproduce or provide a client/server code sample that shows this?  Thanks!

**Comment by rajeshdua123** [comment]
We were sending the compressed data packets to the connected users.  Not sure if that was an issue, but we reverted back to the normal text sending and it started working fine.

**Comment by jchristn** [comment]
Was the CPU utilization associated with the compression or with the library?

**Comment by jchristn** [comment]
Hi @rajeshdua123 closing this - please re-open if you pinpoint that the library is causing high CPU.  Thanks!
