### ISSUE TITLE
Listening on more than one hostname or IP address

### ISSUE THREAD

**Issue by jlopvet** [jchristn/WatsonWebsocket#73]
Hello,

I tried the following on windows 10  and ran as administrator:

`server = new WatsonWsServer("127.0.0.1+host1", 8081, false);`

But this does not work. Could you share an example of listening on more than one host/ip ?

Thank you very much,
Jules

**Comment by jchristn** [comment]
Hi @jlopvet you would want to use this constructor:
```
        /// <summary>
        /// Creates a new instance of the Watson webserver.
        /// </summary>
        /// <param name="hostnames">Hostnames or IP addresses on which to listen.  Note: multiple listener endpoints are not supported on all platforms.</param>
        /// <param name="port">TCP port on which to listen.</param>
        /// <param name="ssl">Specify whether or not SSL should be used (HTTPS).</param>
        /// <param name="defaultRoute">Method used when a request is received and no matching routes are found.  Commonly used as the 404 handler when routes are used.</param>
        public Server(List<string> hostnames, int port, bool ssl = false, Func<HttpContext, Task> defaultRoute = null)
```
For instance:
```
List<string> hostnames = new List<string>
{
  "127.0.0.1",
  "10.1.143.6"
};

Server server = new Server(hostnames, 8000);
```

**Comment by jchristn** [comment]
Please pardon my earlier deleted comment.  It was referring to a different project.

WatsonWebsocket does not support listening on more than one prefix currently.  You would have to spawn an instance for each endpoint.

**Comment by jchristn** [comment]
Hi @jlopvet under the hood it uses ```HttpListener```, which is the same substrate that [Watson Webserver](https://github.com/jchristn/watsonwebserver) uses.  It's reasonable to assume that this project could be amended to also support multiple prefixes.  I'll add it to my list to test out when I get some time, or if you want to give it a go and submit a PR, please feel free!

**Comment by SieBrum** [comment]
Hi @jchristn 

Does this mean that the README.md is incorrect? it currently says:

```
If you want to listen on more than one hostname or IP address, use * or +. You MUST:
Run WatsonWebsocket as administrator for this to work (this is an operating system limitation)
Use the server constructor that takes distinct hostname and port values (not the URI-based constructor)
```

**Comment by jchristn** [comment]
Just uploaded a new version containing a constructor that supports multiple listener prefixes.  Please re-open if any issues!

NuGet: https://www.nuget.org/packages/WatsonWebsocket/2.3.2
Commit: https://github.com/jchristn/WatsonWebsocket/commit/7944cfbdd5fa4af291cdb8369897cf23b1916ca3

```
List<string> hostnames = new List<string>
{
  "192.168.1.163",
  "127.0.0.1"
};

WatsonWsServer server = new WatsonWsServer(hostnames, 8000, false);
```

Cheers, Joel
