### ISSUE TITLE
How does the client set Origin

### ISSUE THREAD

**Issue by manyhelp** [jchristn/WatsonWebsocket#80]
WatsonWsClient.ConfigureOptions();

How to set parameters

**Comment by jchristn** [comment]
Adding @MacKey-255 - this capability was part of their PR and may have some insight.

**Comment by MacKey-255** [comment]
@manyhelp for example:
```
var client = new WatsonWsClient(WebsocketUrl).ConfigureOptions((options) =>
            {
                options.Cookies.Add(new Cookie("mycookie", "value", "/path", WebsocketUrl.DnsSafeHost));
            });
```
The `options` is the instance of the `ClientWebSocketOptions` class, it allow to add options in the WebSocket Client. SAlu2s

**Comment by manyhelp** [comment]
@MacKey-255  not header add Origin

**Comment by manyhelp** [comment]
header add “User-Agent”  "Origin"  "Host"

**Comment by jchristn** [comment]
Thank you @MacKey-255 for chiming in!
