### ISSUE TITLE
Troubles using ssl

### ISSUE THREAD

**Issue by limbo1916** [jchristn/WatsonWebsocket#82]
Hi, I set up ssl wss server using example and wiki guide on my windows 10 machine (with selfsigned certificate). Running in debug mode from administrator i have no issiues to connect to wss server using chrome console either from the same machine or other remote machine using hostname (wss://hostname:port/). But when i create client using watson wsclient it shows "Not connected" status after line:
await client.StartAsync();
I have no trouble when using non ssl server and client. What could be the problem?

**Comment by limbo1916** [comment]
Appears to be 
if (_AcceptInvalidCertificates) ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;
not executing when it encounters invalid certificate chain of untrusted root.

**Comment by limbo1916** [comment]
Apparently ServicePointManager.ServerCertificateValidationCallback  not working in NET.Core. You must use webSocketOptions.RemoteCertificateValidationCallback:

```
 var client = new WatsonWsClient(new Uri("wss://host:port/test/"));
 client = client.ConfigureOptions((webSocketOptions) => {
                webSocketOptions.RemoteCertificateValidationCallback +=
                 (message, certificate, chain, sslPolicyErrors) =>
                 {
                     return true;
                 };
            });
await client.StartAsync();
```

**Comment by jchristn** [comment]
Hi @limbo1916 sorry I'm just seeing this.  Is it working for you now?

**Comment by jchristn** [comment]
The intent of my question is to ask if I need to update the library :)

**Comment by limbo1916** [comment]
It would be great because webSocketOptions working anywhere

**Comment by jchristn** [comment]
Hi @limbo1916 I just updated the library to v2.3.2.5 (see https://www.nuget.org/packages/WatsonWebsocket/2.3.2.5) - could you give it a try and see if it resolves it?

For future reference, it seems the change is only required client-side; the server-side implementation continued to work across .NET 4.6.1, .NET Core 3.1, .NET 5.0, and .NET 6.0.

**Comment by limbo1916** [comment]
Yes it's working now, thanks!
