### ISSUE TITLE
WatsonWebsocket project

### ISSUE THREAD

**Issue by Liryna** [jchristn/WatsonWebsocket#9]
Hi @jchristn ,

Interesting to find this project ! I am always looking to another solution without Edit/Add/Polish it and broken history 👍 
I think people would like to know if you project handle what websocket-sharp can do and specially about performance, memory footprint, multithreaded and how much connection it can handle.
This would motivate people to move to your project (myself include).

Also a CI with tests would be awesome !

I know that it is easier to ask than doing it. I would help you but am already handling different projects myself 😢

**Comment by jchristn** [comment]
Hi @Liryna  :) it is asynchronous and task based.  Memory impact is low, as is CPU.  I haven't tested beyond a dozen concurrent clients though.  Cheers :)
