### ISSUE TITLE
Allocation-free version of Send/Receive

### ISSUE THREAD

**Issue by joreg** [jchristn/WatsonWebsocket#90]
hey joel, 

would you be up for having allocation-free Send/Receive options on the websockets? what do you think of the following:

for send:
https://github.com/jchristn/WatsonWebsocket/blob/6cf7731ab84084c5ed6cb43365fbe77f6d475443/WatsonWebsocket/WatsonWsClient.cs#L642
the internal function is taking an ArraySegment. in our scenario it would come handy if we could just provide that instead of copying to an array first. 

for receive:
https://github.com/jchristn/WatsonWebsocket/blob/6cf7731ab84084c5ed6cb43365fbe77f6d475443/WatsonWebsocket/WatsonWsClient.cs#L602
same here, the internal function is returning an ArraySegment of which currently two copies are made: first into a MemoryStream, then into the buffer (which is also currently allocated twice: L607 and L614). returning an ArraySegment should allow you to get rid of all of this, right?

same is also applicable to the server.

**Comment by jchristn** [comment]
Hi @joreg for sure!  Anything that makes the library more efficient :) Do you have a PR handy by chance?

**Comment by joreg** [comment]
great! no PR handy, but if you prefer, i can attempt one.

**Comment by jchristn** [comment]
That would be awesome @joreg - much appreciated!

**Comment by joreg** [comment]
ok, here is the first part, for sending: #91 
this should be a non-breaking change. 

for the receiving part i'm afraid this would be a minor breaking change, since the MessageReceivedEventArgs will need to have ArraySegment of byte instead of byte[] for data. would you still be accepting this?

**Comment by jchristn** [comment]
Really appreciate you putting this together @joreg - I updated the PR with the NuGet link and the commit.  Thanks!

**Comment by joreg** [comment]
thanks for the quick merge.

and again re the same issue for the receiver. how do you think about a breaking change there as i outlined above?
