### ISSUE TITLE
Use the cancelation token

### ISSUE THREAD

**Issue by MeTitus** [jchristn/WatsonWebsocket#92]
https://github.com/jchristn/WatsonWebsocket/blob/cabf56f9914b87d4485175baaf59379a5e5576bc/src/WatsonWebsocket/WatsonWsServer.cs#L462

Just wondering why you're not using the if expression bellow in the actual while?

if (cancelToken.IsCancellationRequested) break;

**Comment by jchristn** [comment]
Great point, that could certainly be changed :) want to submit a PR?

**Comment by MeTitus** [comment]
The code needs a lot of fixing my friend, this is just one that I spotted today. Great work in getting it all together but it needs to go over a big deal of refactoring. Also, #region and all those comments are not really a thing.

**Comment by jchristn** [comment]
NuGet: https://www.nuget.org/packages/WatsonWebsocket/2.3.5
Commit: https://github.com/jchristn/WatsonWebsocket/commit/3b51689e194e6d6f835ca684a0d0a3726775b27b

Thank you!
